services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqledge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
